apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  selector:
    name: postgres-pod
    app: demo-voting-app
  ports:
  - name: postgres-service
    protocol: TCP
    port: 5432
    targetPort: 5432