apiVersion: v1
kind: Pod
metadata:
  name: "postgres_pod"
  namespace: default
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
  - name: postgres
    image: postgres
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name:  POSTGRES_PASSWORD
      value: "postgres"
    ports:
    - containerPort:  5432
      name:  http