apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  namespace: default
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app-pod
    image: kodekloud/examplevotingapp_result:v1
    ports:
    - containerPort:  80
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi