apiVersion: v1
kind: Service
metadata:
  name: worker-app-service
  labels:
    name: worker-app-service
    app: demo-voting-app
  namespace: default
spec:
  selector:
    name: worker-app-pod
    app: demo-voting-app
  ports:
  - port: 80
    targetPort: 80